config/routes.rb
Rails.application.routes.draw do
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

 devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'articles#index'
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  resources :profile
  resources :articles do
  resources :comments
end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :article
	belongs_to :user
	validates :body , presence: true, allow_blank: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]
    before_action :set_article
     before_action :comment_permission, only: [:edit, :update, :destroy]
     before_action :require_login, only: [:index, :show, :new, :edit ]
    
	def show

	end
	def create
      @comment = Comment.new(comment_params)
      @comment.article_id = params[:article_id]
      @comment.user_id = current_user.id
       @comment.save
      redirect_to article_path(@article)
       flash.notice ='Comment was successfully created.' 
   end
   def edit
   end
   def update
   	respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to article_path(@article), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
   end
   def destroy
   	@comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@article), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
   end
   def set_comment
      @comment = Comment.find(params[:id])
    end
    def set_article
      @article = Article.find(params[:article_id])
    end
    def comment_params
      params.require(:comment).permit(:author, :body)
    end
     def comment_permission
      if user_signed_in?
        if @comment.user_id != current_user.id
          redirect_to article_path(@article)
          flash.notice ='Not your comment' 
        end
      end
    end
 def require_login
   if !user_signed_in? 
    redirect_to root_path
    flash.notice ='Not authorized to do this task' 
    
  end
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [ @article, @comment ], html: {class: 'form-horizontal parsley-validate'} do |f| %>
 <ul>
  <% if @comment.errors.full_messages.any? %>
            <% @comment.errors.full_messages.each do |error_message| %>
              <%= error_message if @comment.errors.full_messages.first == error_message %>
            <% end %>
  <% end %>
  </ul>

      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="comments">

            <div class="comment comment-box">
              <div class="user-photo"> <%= image_tag current_user.photo.url(:small) %></div>
              <div class="comment-body">

                <div class="input-group" style="display: block;">
                  <div class="inputer">
                    <div class="input-wrapper">
                    <%= f.text_area :body , class: 'form-control js-auto-size', :placeholder=>"Enter your Comment",required:true %>
                    </div>
                  </div><!--.inputer-->
                  <br>
                </div><!--.input-group-->
                    <div class="input-group-btn" style="text-align: center;">
                    <%= f.submit class: 'btn btn-primary btn-ripple' %>
                  </div>

              </div><!--.comment-body-->
            </div><!--.comment-->
        </div><!--col-->
      </div><!--row-->
</div><!--row-->
<% end %>

app/views/comments/_show.html.erb
 <h3 style="margin-left: 5%;">Comments:</h3>
<% if @article.comments.present? %>
<div>
   <% @article.comments.each do |comment|%>
      <div class="row" >
        <div class="col-md-10 col-md-offset-2">
          <div class="comments" style="margin: 10px 0px">

            <div class="comment comment-box" style="margin-bottom: 0px; padding-bottom: 0px;">
              <div class="user-photo"> <%= image_tag comment.user.photo.url(:small) %>
              </div>

              <div class="comment-body">
              <h4><%=comment.user.name%></h4>
                  <p id="edit_<%=comment.id%>"><%=comment.body %><br>
                   <% if comment.user_id == current_user.id %>
                       <%= link_to 'Edit', edit_article_comment_path(@article , comment), remote:true;  %> | 
                         <%= link_to 'Destroy', article_comment_path(@article , comment), method: :delete , data: { confirm: 'Are you sure?' } %></p>
                   <%end%>

              </div><!--.comment-body-->
            </div><!--.comment-->
        </div><!--comments-->
      </div><!--col-->
     </div><!--row-->
  <%end%>
  <% else %>
  <div style="margin-left: 6%;">No comments yet.</div>
 <%end%>
 </div>
 

app/views/comments/edit.html.erb
<div class="container">
<h1 style="margin-top: 25px;">Edit a Comment</h1>
<%= render partial: 'form' %>
</div>

<script>
  $(document).ready(function () {
    Pleasure.init();
    Layout.init();

  });
  </script>

app/views/comments/edit.js.erb
$('#edit_<%=@comment.id%>').hide().after('<%= j render partial: ('comments/form')%>')