config/routes.rb
Rails.application.routes.draw do
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

 devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'articles#index'
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  resources :profile
  resources :articles do
  resources :comments
end
end

app/models/article.rb
class Article < ApplicationRecord 
	belongs_to :user
	has_many :comments
	has_many :taggings
    has_many :tags, through: :taggings
	validates :title , presence: true, allow_blank: false
   validates :description , presence: true, allow_blank: false
   has_attached_file :photo, styles: { thumb: "180x180#",small: "300x300>", medium: "500x600>", large:"900x500>" }
   validates_attachment_presence :photo
   validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg','image/jpg', 'image/png']
   
 def tag_list
  self.tags.collect do |tag|
    tag.name
  end.join(", ")
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show ,:edit, :update, :destroy]
  before_action :require_permission, only: [:edit, :destroy]
   before_action :require_login, only: [:new, :edit ]
	
	def index
		@articles = Article.all
	end
	def show
    if user_signed_in?
     @comment = Comment.new
     @comment.article_id = @article.id
     @comment.user_id = current_user.id
   end
	end
	def new
		@article = Article.new

	end
	def create
		@article = Article.new(article_params)
		@article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_path(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
	end
	 def update
	 	@article.user_id = current_user.id
          respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_path(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
   end
     def edit
     end
     def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
private
  def set_article
    @article =Article.find(params[:id])
  
  end
  def article_params
   params.require(:article).permit(:title, :description , :photo , :user_id)
end
def require_permission
  if user_signed_in?
  if @article.user_id != current_user.id
    redirect_to root_path
    flash.notice ='Not your article' 
  end
  end
end
def require_login
   if !user_signed_in? 
    redirect_to root_path
    flash.notice ='You need to SIGN UP / LOG IN.' 
  end
end
 
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true , class: 'form-horizontal  parsley-validate'}) do |f| %>
 
  <ul>
  <% if @article.errors.full_messages.any? %>
            <% @article.errors.full_messages.each do |error_message| %>
              <%= error_message if @article.errors.full_messages.first == error_message %>
            <% end %>
  <% end %>
  </ul>
  
      <div class="row">
      <div class="col-md-12">
        <div class="panel">
          <div class="panel-heading">
            <div class="panel-title"><h4>FORM</h4></div>
          </div><!--.panel-heading-->
          <div class="panel-body">

            <div class="row">
                <div class="form-body">

                  <div class="form-group">
                    <label class="control-label col-md-3">Title</label>
                    <div class="col-md-5">
                      <div class="inputer">
                        <div class="input-wrapper">
                         <%= f.text_field :title , class: 'form-control', required:true %>
                         
                        </div>
                      </div>
                    </div>
                  </div><!--.form-group-->

                  <div class="form-group">
                    <label class="control-label col-md-3">Description</label>
                    <div class="col-md-5">
                      <div class="inputer">
                        <div class="input-wrapper">
                        <%= f.text_area :description , class: 'form-control',required:true %>
                        </div>
                      </div>
                    </div>
                  </div><!--.form-group-->

                </div>
                <div class="form-group">
                  <label class="control-label col-md-3">Image Upload </label><!--.col-md-3-->
              <div class="col-md-5">
                  <div class="fileinput fileinput-new" data-provides="fileinput">
                  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                     <%if @article.photo.exists?%>
                  <%= image_tag @article.photo.url , :size =>'180x140' %>
                  <%end%>
                  </div>
                 
                  <div>
                    <span class="btn btn-default btn-file">
                      <span class="fileinput-new">Select image</span>
                    <span class="fileinput-exists">Change</span>
                    <%if @article.photo.exists?%>
                    <%= f.file_field :photo %></span>
                    <%else%>
                    <%= f.file_field :photo ,required:true%>
                    <%end%>
                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                  </div><!--.col-md-5-->
                </div><!--form-group-->

              </div>
            </div>
            <p>
               <%= f.label :tag_list %><br />
                <%= f.text_field :tag_list %>
            </p>

                 <div class="form-actions">
                  <div class="row">
                    <p style="text-align: center;">
                      <%= f.submit class: 'btn btn-primary btn-ripple' %>
                    </p>
                  </div>
                 </div> 
                 </div><!--form-body-->
            </div><!--.row-->

          </div><!--.panel-body-->
        </div><!--.panel-->
      </div><!--.col-md-12-->
    </div><!--.row-->

<% end %>

app/views/articles/edit.html.erb
<div class="container">
<h1 style="margin-top: 25px;">Edit an Article</h1>
<%= render partial: 'form' %>
</div>

<script>
  $(document).ready(function () {
    Pleasure.init();
    Layout.init();

  });
  </script>

app/views/articles/index.html.erb
<div class="container">
<section>
	<div class="row" >
			<div class="col-md-6">
				<div class="card card-event">
					<div class="card-heading bg-image sample-bg-image12">
					</div><!--.card-heading-->

					<div class="card-body">
						<div class="calendar">
							<div class="month">November</div>
							<div class="date">27</div>
						</div><!--.calendar-->
						
					</div><!--.card-body-->

					<div class="card-footer">
						<div class="btn-group btn-merged btn-group-sm pull-right">
						<h4><%=link_to @articles.first.title , article_path(Article.first) ,:style => 'text-decoration:none;' %></h4>
						  <p><%=truncate(@articles.first.description,length:250)%></p>
							<button type="button" class="btn btn-red btn-flat"> <h4><%= link_to "Popular Blog" , article_path(Article.first) ,:style => 'text-decoration:none;' %></h4></button>
						</div>
					</div><!--.card-footer-->
				</div><!--.card-->
			</div><!--.col-md-6-->

			<div class="col-md-6">
				<div class="card card-event">
					<div class="card-heading bg-image sample-bg-image13">
					</div><!--.card-heading-->

					<div class="card-body">
						<div class="calendar">
							<div class="month">December</div>
							<div class="date">03</div>
						</div><!--.calendar-->
						
					</div><!--.card-body-->

					<div class="card-footer">
					<h4><%=link_to @articles.second.title , article_path(Article.second),:style => 'text-decoration:none;'%></h4>
						  <p><%=truncate(@articles.second.description, length:250)%></p>
						<ul class="users pull-left">
							<li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Emanuele Costa"><img src="assets/globals/1.jpg" alt=""></a></li>
							<li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Sjors Huisman"><img src="assets/globals/2.jpg" alt=""></a></li>
							<li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Isla Olsen"><img src="assets/globals/3.jpg" alt=""></a></li>
							<li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Lydia Gagné"><img src="assets/globals/4.jpg" alt=""></a></li>
							<li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Nicoline Thomsen"><img src="assets/globals/5.jpg" alt=""></a></li>
							<li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Christian Roth"><img src="assets/globals/6.jpg" alt=""></a></li>
							<li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Jonas Verbeke"><img src="assets/globals/7.jpg" alt=""></a></li>
						</ul>
						<button type="button" class="btn btn-sm btn-red btn-flat pull-right"><h4><%= link_to "Popular Blog" , article_path(Article.second) ,:style => 'text-decoration:none;'  %></h4></button>
					</div><!--.card-footer-->
				</div><!--.card-->
			</div><!--.col-md-6-->
		</div><!--.row-->
</section>
</div>
			<div class=" bg-indigo heading" >All Articles</div>
			
<div class="container">
 <div class="row">
    <% @articles.each do |article| %>
			<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
				<div class="card card-deep-purple card-image bg-image ">
                     <p style="text-align: center;"><%= link_to (image_tag article.photo.url(:medium)) , article_path(article) %></p>
					<div class="context">
						<span class="text-title"><%= link_to article.title, article_path(article) %></span>
					</div>

				</div><!--.card-->
			</div><!--.col-->
       <% end %>
     </div>
   
   <div class="display-animation">
			<div class="row image-row">
				<div class="col-sm-6 col-md-3">

					<div class="panel helper-dashboard-height">
						<div class="panel-heading">
							<div class="panel-title"><h4>VISITORS</h4></div>
						</div><!--.panel-heading-->
						<div class="panel-body vertical-padding">
							<div class="gauge-chart">
								<canvas id="gauge" class="gauge-canvas"></canvas>
								<div id="preview-textfield"></div>
								<div class="chart-desc">
									Blog Visitors
								</div>
							</div>
						</div><!--.panel-body-->
					</div><!--.panel-->

				</div><!--.col-->

				<div class="col-sm-6 col-md-3">

					<div class="panel helper-dashboard-height">
						<div class="panel-heading">
							<div class="panel-title"><h4>MAP</h4></div>
						</div><!--.panel-heading-->
						<div class="panel-body">
							<div class="row image-row">
						<div class="col-md-12">
							<div class="card tile card-lime card-image material-animate">
								<input id="pac-input" type="text" placeholder="Search Place" style="    margin-left: 13px;">
								<div id="gmaps-dashboard" class="example-map"></div>
							</div><!--.card-->
						</div><!--.col-->
					</div><!--.row-->

						</div><!--.panel-body-->
					</div><!--.panel-->

				</div><!--.col-->

				<div class="col-sm-12 col-md-6">

					<div class="panel helper-dashboard-height">
						<div class="panel-heading">
							<div class="panel-title"><h4>TIMELINE</h4></div>
						</div><!--.panel-heading-->
						<div class="panel-body horizontal-padding">

							<div class="timeline single helper-timeline">
								<div class="frame">
									<div class="timeline-badge">
										<i class="fa fa-headphones"></i>
									</div><!--.timeline-badge-->
									<span class="timeline-date">17 August 1999</span>
									<div class="timeline-content">
										The 1999 Kocaeli earthquake occurred with a moment magnitude of 7.4 that struck northwestern Turkey struck northwestern Turkey
									</div><!--.timeline-content-->
								</div><!--.frame-->
								<div class="frame">
									<div class="timeline-badge">
										<i class="fa fa-tree"></i>
									</div><!--.timeline-badge-->
									<span class="timeline-date">18 April 1906</span>
									<div class="timeline-content">
										The San Francisco earthquake of 1906 struck San Francisco on Wednesday, April 18, 1906.
									</div><!--.timeline-content-->
								</div><!--.frame-->
							</div><!--.timeline-->

						</div><!--.panel-body-->
					</div><!--.panel-->

				</div><!--.col-->

        </div><!--.row-->
   </div><!--.display-animation-->
</div>
      
	

<script>
	$(document).ready(function () {
		Pleasure.init();
		Layout.init();

		Index.init();
		
	});
	 $('#flash').fadeOut(8000)
	</script>
	<script src="http://maps.google.com/maps/api/js?sensor=true&amp;libraries=places"></script>
 

app/views/articles/new.html.erb
<div class="container">
<h1>Create a New Article</h1>
<%= render partial: 'form' %>
</div>

<script>
  $(document).ready(function () {
    Pleasure.init();
    Layout.init();
    FormsValidationsParsley.init();

  });
  </script>

app/views/articles/show.html.erb
 <div class="container" >
     <div class="row" style="margin-top: -0px;">
		 <div>
			 <%= image_tag @article.photo.url(:large) ,class: "img-responsive" , :style => 'margin: auto;'%>
			</div>
	 </div>
	<div class="content">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center margin-bottom-40" style="margin-top: 50px;"><%= @article.title %></h1>
			</div><!--.col-->
		</div><!--.row-->
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
                <%= @article.description %> 
			</div><!--.col-->
		</div><!--.row-->

       </div><!--content-->
   <div style="text-align: center;margin-top: 20px;" class="table table-hover ">
				<%= link_to "Back", articles_path, class: 'btn btn-primary btn-ripple' %>
           <%if user_signed_in?%>
           <tr>
                   <% if current_user.id == @article.user_id%>
                      <%= link_to "Delete", article_path(@article), method: :delete,data: {confirm: "Really delete the article?"} , class: 'btn btn-primary btn-ripple toastr-notify' %>

                       <%= link_to "Edit", edit_article_path(@article),class: 'btn btn-primary btn-ripple' %>
                   <%end%>
            <%else%>
            <h4 style="margin-top: 20px;">To create your own articles you need to Sign Up!</h4>
           <%end%>
    </div>
      <%if user_signed_in?%>
        <br>
          <%= render partial: 'comments/form' %>
         <br>
          <%= render partial: 'comments/show'%>
      <%end%>
</div><!--container-->

<script>
	$(document).ready(function () {
		Pleasure.init();
		Layout.init();
		FormsValidationsParsley.init();
		
	});

  $('#flash').fadeOut(8000)

	</script>

			